sudo: false
dist: trusty
language: c

matrix:
   include:
      - os: linux
        addons:
           apt:
              sources:
                 - ubuntu-toolchain-r-test
              packages:
                 - gfortran-8
                 - cmake3
                 - libxml2-utils
                 - tree
        env:
           - FC='gfortran-8'
           - CC='gcc-8'
           - CXX='g++-8'
           - USE_MPI=YES
           - MPI_NAME=openmpi-3.1.0
           - CACHE_NAME=linux-gcc8-openmpi310
           - BASELIBS_OS=Linux
           - BASELIBS_VERSION=4.0.11
           - BASELIBS_MPI=openmpi
           - BASELIBS_COMPILER=gfortran

# caching of the whole `local` directory. Can't cache only the one for this
# `env`, because otherwise the different instances will overwrite the cache.
# For the first test-run, the build has to be run sequentially (limit parallel
# workers to 1) so that the cache can be correctly initialized. Once the cache
# is build, parallel workers can be re-enabled.
cache:
   directories:
      - ${HOME}/local
   timeout: 600

before_install:
   - |
      if [ $TRAVIS_OS_NAME == osx ] ; then
         brew cask uninstall oclint || exit 1
         brew install ${BREW} make || exit 1
         brew upgrade ${BREW_UP} || exit 1
      fi

before_script:
   # install MPI
   - mkdir -p ${HOME}/local
   - ls -r ${HOME}/local
   - sh ./src/Config/travis-install-mpi.sh ${MPI_NAME}
   # set up MPI location
   - export PATH=${PATH}:${HOME}/local/${MPI_NAME}/bin
   - export LIBRARY_PATH=${LIBRARY_PATH}:${HOME}/local/${MPI_NAME}/lib
   - export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${HOME}/local/${MPI_NAME}/lib
   - # print out version information
   - ${FC} --version
   - mpirun --version
   # Now build baselibs
   - sh ./src/Config/travis-install-baselibs.sh ${BASELIBS_VERSION} ${BASELIBS_MPI} ${BASELIBS_COMPILER}
   # set up Baselibs location
   - export BASEDIR=${HOME}/local/Baselibs/${BASELIBS_VERSION}
   - export basedir=${HOME}/local/Baselibs/${BASELIBS_VERSION}
   - export PATH=${PATH}:${BASEDIR}/${BASELIBS_OS}/bin
   - export LD_LIBRARY_PATH=${PATH}:${BASEDIR}/${BASELIBS_OS}/lib
   - export DYLD_LIBRARY_PATH=${PATH}:${BASEDIR}/${BASELIBS_OS}/lib
   - export MANPATH=${PATH}:${BASEDIR}/${BASELIBS_OS}/share/man
   - printenv
   # Build GEOS
   - cd ${TRAVIS_BUILD_DIR}
   - mkdir build

script:
   # Build
   - tree -d -L 4 ${HOME}
   #- make -j2
   # Make tests
   #- make -j2 tests
   # Run tests. If the first fails, run with -VV to try and diagnose errors
   #- ctest || ctest -VV

notifications:
   email:
      recipients:
         - matthew.thompson@nasa.gov
         
